// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCredentials() {
  return window['go']['main']['App']['DeleteCredentials']();
}

export function GetAnnouncement() {
  return window['go']['main']['App']['GetAnnouncement']();
}

export function GetCredentials() {
  return window['go']['main']['App']['GetCredentials']();
}

export function GetLatestExe() {
  return window['go']['main']['App']['GetLatestExe']();
}

export function GetRemoteVersion() {
  return window['go']['main']['App']['GetRemoteVersion']();
}

export function ListBugReports(arg1) {
  return window['go']['main']['App']['ListBugReports'](arg1);
}

export function PublishRelease(arg1, arg2) {
  return window['go']['main']['App']['PublishRelease'](arg1, arg2);
}

export function ResolveBugReport(arg1, arg2) {
  return window['go']['main']['App']['ResolveBugReport'](arg1, arg2);
}

export function SaveAnnouncement(arg1) {
  return window['go']['main']['App']['SaveAnnouncement'](arg1);
}

export function SaveCredentials(arg1) {
  return window['go']['main']['App']['SaveCredentials'](arg1);
}

export function ValidateCredentials(arg1) {
  return window['go']['main']['App']['ValidateCredentials'](arg1);
}
