// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {credentials} from '../models';

export function DeleteCredentials():Promise<void>;

export function GetAnnouncement():Promise<main.Announcement>;

export function GetCredentials():Promise<credentials.Credentials>;

export function GetLatestExe():Promise<main.ExeInfo>;

export function GetRemoteVersion():Promise<main.VersionInfo>;

export function ListBugReports(arg1:number):Promise<main.BugListResult>;

export function PublishRelease(arg1:string,arg2:string):Promise<void>;

export function ResolveBugReport(arg1:number,arg2:string):Promise<void>;

export function SaveAnnouncement(arg1:main.Announcement):Promise<void>;

export function SaveCredentials(arg1:credentials.Credentials):Promise<void>;

export function ValidateCredentials(arg1:credentials.Credentials):Promise<void>;
