// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function BackupDB():Promise<string>;

export function CopyPreviousDay(arg1:number,arg2:string):Promise<models.Attendance>;

export function CreateAdvance(arg1:number,arg2:string,arg3:number,arg4:string):Promise<models.Advance>;

export function CreateTeamUser(arg1:string,arg2:number):Promise<models.User>;

export function CreateWorksite(arg1:string,arg2:number):Promise<models.Worksite>;

export function DeleteAdvance(arg1:number):Promise<void>;

export function DeleteAttendance(arg1:number):Promise<void>;

export function DeleteTeamUser(arg1:number):Promise<void>;

export function DeleteWorksite(arg1:number):Promise<void>;

export function EnsureSelfUser(arg1:string,arg2:number):Promise<models.User>;

export function ExportPDF(arg1:number,arg2:string,arg3:string):Promise<string>;

export function GetAuditLog(arg1:number,arg2:number):Promise<Array<models.AuditLog>>;

export function GetMonthAdvances(arg1:number,arg2:string):Promise<Array<models.Advance>>;

export function GetMonthAttendance(arg1:number,arg2:string):Promise<Array<models.Attendance>>;

export function GetMonthSummary(arg1:number,arg2:string):Promise<models.MonthSummary>;

export function GetSelfUser():Promise<models.User>;

export function GetTeamUsers():Promise<Array<models.User>>;

export function GetToday():Promise<string>;

export function GetWorksiteSummary(arg1:number,arg2:string):Promise<Array<models.WorksiteSummary>>;

export function GetWorksites():Promise<Array<models.Worksite>>;

export function RestoreDB():Promise<void>;

export function UpdateAdvance(arg1:number,arg2:string,arg3:number,arg4:string):Promise<void>;

export function UpdateUser(arg1:number,arg2:string,arg3:number):Promise<void>;

export function UpdateWorksite(arg1:number,arg2:string,arg3:number):Promise<void>;

export function UpsertAttendance(arg1:number,arg2:string,arg3:number,arg4:any,arg5:string):Promise<models.Attendance>;
