// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupDB() {
  return window['go']['main']['App']['BackupDB']();
}

export function CopyPreviousDay(arg1, arg2) {
  return window['go']['main']['App']['CopyPreviousDay'](arg1, arg2);
}

export function CreateAdvance(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateAdvance'](arg1, arg2, arg3, arg4);
}

export function CreateTeamUser(arg1, arg2) {
  return window['go']['main']['App']['CreateTeamUser'](arg1, arg2);
}

export function CreateWorksite(arg1, arg2) {
  return window['go']['main']['App']['CreateWorksite'](arg1, arg2);
}

export function DeleteAdvance(arg1) {
  return window['go']['main']['App']['DeleteAdvance'](arg1);
}

export function DeleteAttendance(arg1) {
  return window['go']['main']['App']['DeleteAttendance'](arg1);
}

export function DeleteTeamUser(arg1) {
  return window['go']['main']['App']['DeleteTeamUser'](arg1);
}

export function DeleteWorksite(arg1) {
  return window['go']['main']['App']['DeleteWorksite'](arg1);
}

export function EnsureSelfUser(arg1, arg2) {
  return window['go']['main']['App']['EnsureSelfUser'](arg1, arg2);
}

export function ExportPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportPDF'](arg1, arg2, arg3);
}

export function GetAuditLog(arg1, arg2) {
  return window['go']['main']['App']['GetAuditLog'](arg1, arg2);
}

export function GetMonthAdvances(arg1, arg2) {
  return window['go']['main']['App']['GetMonthAdvances'](arg1, arg2);
}

export function GetMonthAttendance(arg1, arg2) {
  return window['go']['main']['App']['GetMonthAttendance'](arg1, arg2);
}

export function GetMonthSummary(arg1, arg2) {
  return window['go']['main']['App']['GetMonthSummary'](arg1, arg2);
}

export function GetSelfUser() {
  return window['go']['main']['App']['GetSelfUser']();
}

export function GetTeamUsers() {
  return window['go']['main']['App']['GetTeamUsers']();
}

export function GetToday() {
  return window['go']['main']['App']['GetToday']();
}

export function GetWorksiteSummary(arg1, arg2) {
  return window['go']['main']['App']['GetWorksiteSummary'](arg1, arg2);
}

export function GetWorksites() {
  return window['go']['main']['App']['GetWorksites']();
}

export function RestoreDB() {
  return window['go']['main']['App']['RestoreDB']();
}

export function UpdateAdvance(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateAdvance'](arg1, arg2, arg3, arg4);
}

export function UpdateUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateUser'](arg1, arg2, arg3);
}

export function UpdateWorksite(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateWorksite'](arg1, arg2, arg3);
}

export function UpsertAttendance(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpsertAttendance'](arg1, arg2, arg3, arg4, arg5);
}
